### ISSUE TITLE
can't create sdbclient for public user i.e. without username 

### ISSUE THREAD

**Issue by mdobrzanski** [SlashDB/react-slashdb#7]
Let's say the slashdb instance allows public access, like default docker intance gives access to sqlite Chinook database

I should be able to setup provider without username and password
```
<SlashDBProvider
       baseUrl='http://localhost:8001'
       setUpOptions={{
         // username: 'public',
         // password: process.env.REACT_APP_DATABASE_PASSWORD,
         // apiKey: 'aaa',
       }}
     >
        <App />
     </SlashDBProvider>
```
and then setup and get resources
```
const sdbClient = useSetUp();
  const [lists, getList, postList, putList, deleteList] = useDataDiscovery(
    'Chinook',
    'Customer'
  );
```
instead I got errors in console

```
slashdbclient.js:31 Uncaught TypeError: Invalid username parameter, must be string
    at new SlashDBClient (slashdbclient.js:31:1)
    at useSetUp (hooks.js:29:1)
    at App (App.js:7:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
SlashDBClient @ slashdbclient.js:31
useSetUp @ hooks.js:29
App @ App.js:7
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
slashdbclient.js:31 Uncaught TypeError: Invalid username parameter, must be string
    at new SlashDBClient (slashdbclient.js:31:1)
    at useSetUp (hooks.js:29:1)
    at App (App.js:7:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
SlashDBClient @ slashdbclient.js:31
useSetUp @ hooks.js:29
App @ App.js:7
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18687 The above error occurred in the <App> component:

    at App (http://localhost:3000/static/js/bundle.js:86:85)
    at SlashDBProvider (http://localhost:3000/static/js/bundle.js:2770:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
slashdbclient.js:31 Uncaught TypeError: Invalid username parameter, must be string
    at new SlashDBClient (slashdbclient.js:31:1)
    at useSetUp (hooks.js:29:1)
    at App (App.js:7:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
SlashDBClient @ slashdbclient.js:31
useSetUp @ hooks.js:29
App @ App.js:7
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

I was able to walkaround it by providing wrong credentials. Unauthenticated user drops to "public" user.

**Comment by jhslashdb** [comment]
fixed, created a default parameter for user argument, set to 'public' - if username is 'public', apiKey and password arguments are also set to 'public', unless other values are given

**Comment by mdobrzanski** [comment]
Would it be possible not to send anything?

**Comment by jhslashdb** [comment]
issue fixed, documentation updates still pending
