### ISSUE TITLE
calling useSetUp is necessary and wrong error message

### ISSUE THREAD

**Issue by mdobrzanski** [SlashDB/react-slashdb#8]
Error message is misleading using hooks without calling useSetUp before or useSetUp should be called differently. 

The docs only suggest that useSetUp should be called early "It is good practice to call it at the near top level" but apparently it's necessary.

![useSetUp-invalid-case](https://user-images.githubusercontent.com/807888/194910532-595381c1-7373-4761-a75d-fd2c6b4f19f9.png)

Below is simple App

```
import { useContext } from 'react';

import { useDataDiscovery } from "@slashdb/react-slashdb";
import { useSetUp } from '@slashdb/react-slashdb';
import { SlashDBContext } from '@slashdb/react-slashdb';

function App() {
  const { baseUrl, setUpOptions } = useContext(SlashDBContext);
  // const sdbClient = useSetUp('local', 'http://localhost:8001', 'a', 'a');
  const [
    customers,
    getCustomers,
    createCustomers,
    updateCustomers,
    deleteCustomers
  ] = useDataDiscovery(
      'Chinook',
      'Customer',
      '/Country/Brazil',
      'local'
  );

  const customerListElement = customers.map((c, idx) => (
    <li key={idx}>
      {c.FirstName} {c.LastName}
    </li>
  ));

  return (
    <div className="App">
        <ol>{customerListElement}</ol>
    </div>
  );
}

export default App;

```

 if the line `const sdbClient = useSetUp('local', 'http://localhost:8001', 'a', 'a');`  is commented out, then the error in console `Parameter db must be a string or a DataDiscoveryDatabase` is misleading

```
datadiscovery.js:108 Uncaught ReferenceError: Parameter db must be a string or a DataDiscoveryDatabase object
    at new DataDiscoveryResource (datadiscovery.js:108:1)
    at useDataDiscovery (hooks.js:74:1)
    at App (App.js:10:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
DataDiscoveryResource @ datadiscovery.js:108
useDataDiscovery @ hooks.js:74
App @ App.js:10
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
datadiscovery.js:108 Uncaught ReferenceError: Parameter db must be a string or a DataDiscoveryDatabase object
    at new DataDiscoveryResource (datadiscovery.js:108:1)
    at useDataDiscovery (hooks.js:74:1)
    at App (App.js:10:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
DataDiscoveryResource @ datadiscovery.js:108
useDataDiscovery @ hooks.js:74
App @ App.js:10
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18687 The above error occurred in the <App> component:

    at App (http://localhost:3000/static/js/bundle.js:37:56)
    at SlashDBProvider (http://localhost:3000/static/js/bundle.js:2699:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
datadiscovery.js:108 Uncaught ReferenceError: Parameter db must be a string or a DataDiscoveryDatabase object
    at new DataDiscoveryResource (datadiscovery.js:108:1)
    at useDataDiscovery (hooks.js:74:1)
    at App (App.js:10:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
DataDiscoveryResource @ datadiscovery.js:108
useDataDiscovery @ hooks.js:74
App @ App.js:10
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

**Comment by jhslashdb** [comment]
documentation updated to clarify, casing in `useSetUp` corrected
